TheCenturiaGames/Sobrassada_Engine

- SobrassadaEngine/UI/EditorUIModule.h
> Formatted header file

- Game/Test/skyboxFragment.glsl
- Game/Test/skyboxVertex.glsl
- SobrassadaEngine/Modules/DebugDrawModule.cpp
- SobrassadaEngine/Modules/OpenGLModule.cpp
- SobrassadaEngine/Modules/OpenGLModule.h
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
- SobrassadaEngine/Tests/RenderTestModule.cpp
- SobrassadaEngine/Tests/RenderTestModule.h
- SobrassadaEngine/Tests/TextureModuleTest.cpp
- SobrassadaEngine/Tests/TextureModuleTest.h
- SobrassadaEngine/Utils/LightsConfig.cpp
- SobrassadaEngine/Utils/LightsConfig.h
Debug grid draw is called from RenderTestModule.cpp because skybox mus be first to be drawn. Added a method in TextureModuleTest to load cubemaps.
> Skybox render

- SobrassadaEngine/FileSystem.cpp
- SobrassadaEngine/FileSystem.h
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
- SobrassadaEngine/UI/EditorUIModule.cpp
- SobrassadaEngine/UI/EditorUIModule.h
- SobrassadaEngine/Utils/Globals.h
New option added in main menu window "Import", opens a new window that is basically a simple file explorer. 
This dialog has the following features:
· Navigate through paths.
· Go to drives folder.
· Search introducing text for a specific file.
· Select file to import.
Import functionality has to be connected with binaryFiles branch, this is only the UI.
> Import dialog

- SobrassadaEngine/Modules/WindowModule.cpp
- SobrassadaEngine/Modules/WindowModule.h
- SobrassadaEngine/UI/EditorUIModule.cpp
- SobrassadaEngine/UI/EditorUIModule.h
- SobrassadaEngine/Utils/Globals.h
Features implemented:
· Added some information about the engine
· Vsync checkbox
· Slider for fps
Now in editor settings window from menu there is an Application section which has some information about the engine, a slider for selecting the frame rate and frames graph display. 
In window section there is a checkbox for enable/disable vsync.
If vsync disabled and slider for fps = 0 → unlimited fps.
> Limit Framerate

- SobrassadaEngine/Modules/InputModule.h
- SobrassadaEngine/UI/EditorUIModule.cpp
- SobrassadaEngine/UI/EditorUIModule.h
- SobrassadaEngine/Utils/Globals.h
· Added input keyboard, mouse buttons and mouse information in runtime.
· Added hardware specs information, as we had in the first assignment.
· Added new menu option About. With some description about our engine, reference links, libraries and build/config options.
· Also fixed a warning from limit fps and added const.
How to test:
About window is in the top menu bar.
Hardware and input are collapsed widgets inside editor settings.
> Editor input, hardware & aboutUs

- SobrassadaEngine/FileSystem/MeshImporter.cpp
- SobrassadaEngine/FileSystem/TextureImporter.cpp
- SobrassadaEngine/Modules/LibraryModule.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceMesh.cpp
- SobrassadaEngine/Scene/Components/Root/RootComponent.cpp
- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/UI/EditorUIModule.cpp
- SobrassadaEngine/UI/EditorUIModule.h
- SobrassadaEngine/Utils/EngineTimer.cpp
- SobrassadaEngine/Utils/LightsConfig.cpp
- SobrassadaEngine/Utils/Scene.cpp
- SobrassadaEngine/Utils/Scene.h
Things added:
· Fixed a bug when creating empty scene, directionalLight was nullptr and was crashing.
· Fixed the bug of docking imgui windows inside scene window.
· Fixed all warnings from second assignment.
· Polished menu bar to File and Window and bool tick for those windows that are being displayed.
How to test:
Try creating a new scene and moving all windows inside others.
> THO-167 Bug/stack windows

- SobrassadaEngine/Scene/Components/Standalone/Lights/DirectionalLightComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Lights/SpotLightComponent.cpp
Small fix with merge, only staged pushed.
Missing "Component" in SpotLight and DirectionalLight.
> Small fix with merge

- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Modules/EditorUIModule.h
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
- SobrassadaEngine/UI/EngineEditors/Editor/TextureLibraryEditor.cpp
- SobrassadaEngine/UI/EngineEditors/Editor/TextureLibraryEditor.h
Before creating the pull request, here’s a summary:
- Implemented the Texture Library Editor to list and display loaded textures.
- Added columns for name, width, height, and memory size in KB.
- Fixed issues with texture preview display, ensuring textures render correctly when selected.
- Addressed some errors related to ResourceTexture and ImTextureID compatibility.
The task is not yet fully finished, but I will create the PR now to avoid merge conflicts. I have tested the changes, and I don’t believe they break anything in the main branch. However, let me know if you notice any unexpected issues. I will continue working on a new branch after the merge.
> Texture editor THO-153

- Game/EngineDefaults/Shader/Fragment/BRDFCookTorranceShader.glsl
- Game/EngineDefaults/Shader/Fragment/BRDFPhongFragmentShader.glsl
- SobrassadaEngine/Main.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
Testing: Don't use an intel GPU, they're stupid as fuck
> Bug/problem with textures THO-230

- SobrassadaEngine/SobrassadaEngine.vcxproj
Also noticed recast was included twice in debug.
All branches should work now
> Fix vcxproj

- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
Fix to GameObject flying away.
> Fix to objects flying away when input value in local space

- SobrassadaEngine/Main.cpp
- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Modules/InputModule.cpp
- SobrassadaEngine/Modules/LibraryModule.cpp
- SobrassadaEngine/Modules/OpenGLModule.cpp
- SobrassadaEngine/Modules/ShaderModule.cpp
- SobrassadaEngine/Modules/WindowModule.cpp
- SobrassadaEngine/Scene/Components/ScriptComponent.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ButtonScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ButtonScript.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/GodMode.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/GodMode.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/RotateGameObject.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/RotateGameObject.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
- SobrassadaEngine/Utils/LightsConfig.cpp
- SobrassadaEngine/Utils/LightsConfig.h
- SobrassadaEngine/Utils/Script.h
As I added ImGui, we need to add specific saving and loading from scripts. Also I cleaned the console.
Testing: Just add RotateGameObject Script, change the values and save/load the scene
> THO-392 save/load scripting

- SobrassadaEngine/Modules/DebugDrawModule.cpp
- SobrassadaEngine/Scene/Components/Component.cpp
- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/Utils/log.cpp
Test:
You can click F12 to see render options to check tomorrow on class while we play. You can click play and see its working. I also limited the messages for the console.
> THO-396 camera debug

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
> Fix filters in SobrassadaScripts

- SobrassadaEngine/FileSystem/StateMachineManager.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.h
- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.h
- SobrassadaEngine/UI/EngineEditors/Editor/StateMachineEditor.cpp
- SobrassadaEngine/UI/EngineEditors/Editor/StateMachineEditor.h
- SobrassadaEngine/Utils/HashString.h
Now state machines are still a resource but the active state has been moved to the animation component allowing multiple components to use the same state machine without affecting others.
If you don't have a model with different animations you can use this one, to build and test a state machine.
[Fox.zip](https://github.com/user-attachments/files/20015143/Fox.zip)
> THO-460 Multi use state machine

- SobrassadaEngine/FileSystem/PrefabManager.cpp
- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Modules/LibraryModule.cpp
- SobrassadaEngine/Modules/LibraryModule.h
- SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp
- SobrassadaEngine/Scene/Scene.cpp
Now updating a prefab overwrites the existing one. Also added capability to delete prefabs from the load prefab menu.
Also fixed an issue that made prefabs spawn at 000 when loading a scene
> THO-464 Prefab fixing

- SobrassadaEngine/ResourceManagement/Resources/ResourceTexture.cpp
Solved the problem with memory leaks when you click play/stop
> THO-355 fix memory leaks

- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/Scene/Scene.cpp
Test: You can do right-click on the hierarchy window and create a new GameObject
> THO-486 add new game object

- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp
There has been one merge confict with string hashes, just a line
> Compiling error fix

- SobrassadaEngine/Scene/Scene.cpp
Test: Just have some model in the scene and click on the wireframe debug option
> THO-483 wireframe rendering broken

- SobrassadaEngine/FileSystem/Importers/AnimationImporter.cpp
- SobrassadaEngine/FileSystem/Importers/MaterialImporter.cpp
- SobrassadaEngine/FileSystem/Importers/MeshImporter.cpp
- SobrassadaEngine/FileSystem/Importers/ModelImporter.cpp
- SobrassadaEngine/FileSystem/Importers/NavmeshImporter.cpp
- SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp
- SobrassadaEngine/FileSystem/Importers/TextureImporter.cpp
- SobrassadaEngine/FileSystem/StateMachineManager.cpp
- SobrassadaEngine/Modules/LibraryModule.cpp
- SobrassadaEngine/Modules/OpenGLModule.cpp
- SobrassadaEngine/Modules/PathfinderModule.cpp
- SobrassadaEngine/Modules/PathfinderModule.h
- SobrassadaEngine/Modules/SceneModule.cpp
- SobrassadaEngine/Modules/ScriptModule.cpp
- SobrassadaEngine/Scene/Components/Standalone/AnimController.cpp
- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Audio/AudioSourceComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/UI/ButtonComponent.cpp
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ButtonScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ExitGameScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/PressAnyKeyScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/RotateGameObject.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Soldier.cpp
- SobrassadaEngine/UI/EngineEditors/Editor/StateMachineEditor.cpp
- SobrassadaEngine/Utils/LightsConfig.cpp
Test: You can try scenes with navmesh and scenes that does not have a navmesh. I left in engineTest in a branch called navmesh 3 different scenes. 2 With navmesh and 1 without.
Also cleared all the glogs that are not an error
> THO-501 navmesh load on scene change

- SobrassadaEngine/FileSystem/PrefabManager.cpp
- SobrassadaEngine/Modules/GameUIModule.cpp
- SobrassadaEngine/Scene/Components/CameraComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
FIxes the aiming and attacking direction of the player in game and gameDebug mode.
To test: execute the engine in game or gameDebug and see if it aims and attacks towards where the mouse is
Also fixed that characterController rotation in radians was applied as degrees anyway
> Fix aiming in game mode

- SobrassadaEngine/Modules/AudioModule.cpp
- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Modules/EditorUIModule.h
- SobrassadaEngine/Modules/ScriptModule.cpp
- SobrassadaEngine/Modules/ScriptModule.h
- SobrassadaEngine/ResourceManagement/Resources/ResourcePrefab.cpp
- SobrassadaEngine/Scene/Components/ScriptComponent.cpp
- SobrassadaEngine/Scene/Components/ScriptComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Audio/AudioSourceComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Audio/AudioSourceComponent.h
- SobrassadaEngine/Scene/Components/Standalone/UI/Transform2DComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/UI/Transform2DComponent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Wwise_IDs.h
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
For testing: In dev-testing there is an scene called spawnTesting with a sound. You can check that it does not crash and its good.
Also added the case insensitive for searching components or meshes/materials
> THO-361 project specific scripting

- SobrassadaEngine/Modules/InputModule.cpp
- SobrassadaEngine/Modules/InputModule.h
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
To test this PR, connect a game controller (tested with a PS5 DualSense controller) and run the engine. 
Move the analog sticks, press triggers and buttons — logs will be printed to the console showing their state. This verifies that controller input is being correctly read and processed.
I tested with: PlayStation 5 DualSense Controller.
> Controller-Support-THO-498

- SobrassadaEngine/Modules/PhysicsModule.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/CapsuleColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/CapsuleColliderComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Physics/CubeColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/CubeColliderComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Physics/SphereColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/SphereColliderComponent.h
- SobrassadaEngine/Utils/Physics/BulletMotionState.cpp
- SobrassadaEngine/Utils/Physics/BulletMotionState.h
Changed collider editor to use drag floats to make it simple to adapt use.
Note: for weapon colliders use capsule collider instead of cube, leave those for triggers
> THO-599 Improvement to collider editor

- SobrassadaEngine/FileSystem/FileSystem.h
- SobrassadaEngine/Modules/ScriptModule.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj
These changes should solves the scripting error. The problem was that the .lib was generated but in another place so the new scripts were using the old lib. Now you wont have the problem.
> THO-607 Solving error

- SobrassadaEngine/Modules/InputModule.cpp
- SobrassadaEngine/Modules/InputModule.h
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CameraMovement.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CameraMovement.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
Adapted the player actions to a controller. I used as a reference for the controls this image, only with the actions we have now. 
It should still work with keyboard as well, test that too just in case. You can test this in any scene with the player, for example the spawnTesting one
> Task/Player controller controls THO-591

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
Implemented the first trap that consists in a fireball falling into a certain spot causing an area of damage for a certain period of time. This trap activates every x time. In the new script named FireballTrap, there are loads of variables to tweak to put it to your liking. Also, created a model that contains the plane where fireball with impact with the model that the artists gave us.
How to test:
In EngineTests repository branch dev-testing, there is a scene called FireTrapTesting where this feature can be tested properly.
> Task/Fireball Trap THO- 500

- SobrassadaEngine/Modules/BillboardModule.cpp
- SobrassadaEngine/Scene/Components/CameraComponent.h
- SobrassadaEngine/Utils/Particles/Billboard.cpp
- SobrassadaEngine/Utils/Particles/Billboard.h
Forgot to add the current rendering camera when rendering the billboards, now billboards shoud face the camera in play mode
> THO-609 Rendering billboards render bug

- SobrassadaEngine/Modules/InputModule.cpp
- SobrassadaEngine/Modules/InputModule.h
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
Improved some of the controls and player features:
- Fixed the player snapping to the axis directions
- Slide along the edges instead of stopping
- When falling after a dash, respawn in the last position after surpassing a y pos threshold
- Move along the camera axes, so moving down the joystick with a rotated camera actually goes down from the player perspective
- Detection of controller connection anytime, not just when opening the engine
> Player improvements

- SobrassadaEngine/Scene/Components/ScriptComponent.cpp
Just click play and stop with an enabled script
> THO-633 Scripts disabled after stop playing

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/TileFloatScript.cpp
distance to player now adds world position to the finalPoisiton (localposition). 
You can now input negative values in the start position
> BugfixTilefloatUpdate-THO-632

- SobrassadaEngine/Scene/Components/Standalone/UI/CanvasComponent.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.h
Created a script to show tutorial images instructions from a trigger collision.
How to test:
In HoundOfUlster repository there is a branch named tutorialChanges and in tutorial scene you can test this feature.
To test it yourself, create a canvas and a children image component with an image. Then in another game object create a sphere collider with trigger tag and add the script SpawnUI puting the name of the game object containing the image.
> Task/Tutorial Instructions THO-608

- SobrassadaEngine/Modules/DebugDrawModule.cpp
- SobrassadaEngine/Modules/SceneModule.cpp
- SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/Scene/Scene.h
Change dynamic tree to be octree.
Load a scene, and everything should keep working
> THO-639 Change Dynamic tree

- SobrassadaEngine/Modules/DebugDrawModule.cpp
- SobrassadaEngine/Modules/DebugDrawModule.h
- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Scene/Components/Component.cpp
- SobrassadaEngine/Scene/Components/Component.h
- SobrassadaEngine/Scene/Components/ComponentUtils.cpp
- SobrassadaEngine/Scene/Components/ComponentUtils.h
- SobrassadaEngine/Scene/Components/Standalone/SplineComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/SplineComponent.h
- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/Scene/GameObjects/GameObject.h
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
Now it is available the Spline Component!
With it we can develop different functionalities with scripts such as automated Camera Movement, better patrolling for enemies, etc.
How to test it:
- There is a scene as an example in dev-testing. Open that scene or create a new one from zero.
- In render Options, remember to hit the Spline checkbox in order to always see the splines in the scene. If this is not done, you'll only see them when Game Object containing Spline component is selected.
- (If you have created a new scene from zero) add the spline component and then add some points. Then if you select a point, you can move it with the gizmos. (Take into account that, if a point is selected, **the GameObject Transform and gizmos will be** **deactivated** in order to avoid unexpected …
> Task/spline component THO-43

- SobrassadaEngine/Scene/Components/Component.cpp
- SobrassadaEngine/Scene/Components/Component.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Archer.cpp
Implemented archer with animations. Little code changes were needed. Also now patrol point goes from -1000 to 1000 in editor
To test: in EnemiesImplementation in The Hound of Ulster repo there is now the archer prefab, place it anywhere and see if it works.
> Task/Archer V2 THO-492

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Archer.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
Player dash cooldown can be modified from the editor
> Player dash cooldown

- Game/EngineDefaults/Shader/Fragment/DecalFragment.glsl
- Game/EngineDefaults/Shader/Vertex/DecalVertex.glsl
- SobrassadaEngine/Modules/EditorUIModule.cpp
- SobrassadaEngine/Modules/ShaderModule.cpp
- SobrassadaEngine/Modules/ShaderModule.h
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
- SobrassadaEngine/Scene/Components/ComponentUtils.cpp
- SobrassadaEngine/Scene/Components/ComponentUtils.h
- SobrassadaEngine/Scene/Components/Standalone/DecalComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/DecalComponent.h
- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/Scene/GameObjects/GameObject.h
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/Scene/Scene.h
- SobrassadaEngine/SobrassadaEngine.vcxproj
- SobrassadaEngine/SobrassadaEngine.vcxproj.filters
- SobrassadaEngine/Utils/Globals.h
I made a branch in EngineTest called Decals. You can put a decal component if you want but needs to face the Z direction. (If you see the decal bad, basically you need to rotate)
> THO-565 Decals

- Game/EngineDefaults/Shader/Fragment/BillboardFragment.glsl
- Game/EngineDefaults/Shader/Vertex/BillboardVertex.glsl
- SobrassadaEngine/Modules/BillboardModule.cpp
- SobrassadaEngine/Modules/BillboardModule.h
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
- SobrassadaEngine/Scene/Components/Standalone/BillboardComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/BillboardComponent.h
- SobrassadaEngine/Scene/Scene.cpp
- SobrassadaEngine/Utils/Particles/Billboard.cpp
- SobrassadaEngine/Utils/Particles/Billboard.h
Now transparency is working and also added the option to modify the billboard texture range to just use a part of the whole texture.
> THO-621 Advanced billboards

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Banshee.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Banshee.h
Added some visuals to banshee attack, so the player has more feedback when getting damage.
Visuals are placeholders.
How to test:
Go to HoundOfUlster, branch lg-final-revision and check scene level 2 banshees.
> Task/Banshee Attack Visual THO_679

- SobrassadaEngine/FileSystem/StateMachineManager.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.h
- SobrassadaEngine/Scene/Components/Standalone/AnimController.cpp
- SobrassadaEngine/Scene/Components/Standalone/AnimController.h
- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.h
- SobrassadaEngine/UI/EngineEditors/Editor/StateMachineEditor.cpp
This PR allows the speed of the animation be controlled independently in the state machine editor. 
How to Test: Open the Hound of Ulster repo, go to tutorial (where the prefab of player is), select player, open de state machine editor and load the player state machine, in the different states should be a slider with the name animation speed, tinker with it and put the states with different speeds. You can check how the speed is affecting the animation by  pressing the triggers, the transition should look good and the animation speed remain independent in both clips.
> Task/Animation speed parameter-THO-656 

- SobrassadaEngine/Scene/Components/Standalone/TrailComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/TrailComponent.h
It solves this error in a prefab
> bug/THO-740 Trail bug with color in prefabs

- SobrassadaEngine/.vscode/settings.json
- SobrassadaEngine/Modules/PhysicsModule.cpp
- SobrassadaEngine/Scene/Components/ComponentUtils.h
- SobrassadaEngine/Scene/Components/ScriptComponent.cpp
- SobrassadaEngine/Scene/Components/ScriptComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Physics/CapsuleColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/CapsuleColliderComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Physics/CubeColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/CubeColliderComponent.h
- SobrassadaEngine/Scene/Components/Standalone/Physics/SphereColliderComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Physics/SphereColliderComponent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ChangeSceneScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ChangeSceneScript.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Mushroom.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Mushroom.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.h
- SobrassadaEngine/Utils/Physics/BulletUserPointer.h
- SobrassadaEngine/Utils/Script.h
Changes the behaviour of changing the collider type so it no longer changes the hierarchy of the GO, also has the changes for [THO-706](https://fpcvideogames.youtrack.cloud/issue/THO-706) Layers OnCollision.
> THO-715 Mobility with colliders

- SobrassadaEngine/Scene/GameObjects/GameObject.cpp
- SobrassadaEngine/Scene/Scene.cpp
Multiselect broke with one of the recent PR, now should be fixed
> THO-739 Multiselect broken

- SobrassadaEngine/FileSystem/StateMachineManager.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
Fixes the game crash when player dies.
> Fixed crash because of null ptr from component

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
How to test:
HoundOfUlster branch RangeAttackVisual and try to range attack.
> task/Range attack visual THO-678

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Mushroom.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Mushroom.h
Mushrooms now have an inventory (max 3).
How to test:
HoundOfUlster branch Inventory Mushrooms and take test with first mushroom.
For checking life or mushrooms quantity enable debug visuals since health connection is not working there.
Keyboard: E for taking it and R for using it.
Game pad: R1 for taking it and L1 for using it.
> task/InventoryMushrooms THO-719

- SobrassadaEngine/Scene/Components/Standalone/AIAgentComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/AIAgentComponent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Soldier.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Soldier.h
A first version of the knockback when a soldier is hitted.
For testing open any scene with soldiers in any branch of the game repo 
Now when you hit an enemy they stop what they are doing for having a knockback in the direction it was hitted. 
The animation changes to the idle one but it will be changed to a hitted one in the future.
The distance of the knockback and the time the enemy is stunned can be changed in the inspector.
I'ts a first version that can be improved when we have more time after alpha 1. Any improvement ideas are welcomed.
> Task/Soldier knock back V1 -THO-754

- SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/MeshComponent.h
- SobrassadaEngine/Scene/RenderPass.cpp
> Task/THO-758 shadow activate / deactive

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.h
Now this shaders take the proper model transfrom for meshes
> Fix to movingUV shader global transform

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.h
- SobrassadaEngine/Utils/Script.h
This just adds a Reset function to all scripts, can be usefull at least in shader scripts to reset some variables without the need of using the Init function. Also increases the cap of animation speed of Moving UV shaders to 100, prev 1, forgot to change it :D
> THO-875 Shader scripts adjustments

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.h
Script changes to initiate the blooming of the tree of life when it gets activated.
For testing, open the same branch in the game repo and add the prefab EN_TreeOfLife to a level. Then walk close to the tree. The mesh will be updated later, for this pr its just important that the animation is played
> Blooming tree of life THO-922

- Game/EngineDefaults/Shader/Custom/Fragment/MovingUV_Transparent_Fragment.glsl
- Game/EngineDefaults/Shader/Fragment/BRDFCookTorranceShader.glsl
- Game/EngineDefaults/Shader/Fragment/BRDFPhongFragmentShader.glsl
- Game/EngineDefaults/Shader/Fragment/IBLShader.glsl
- Game/EngineDefaults/Shader/Fragment/UnlitFragmentShader.glsl
- Game/EngineDefaults/Shader/Fragment/gBufferMetallicFragment.glsl
- Game/EngineDefaults/Shader/Fragment/gBufferSpecularFragment.glsl
- Game/EngineDefaults/Shader/Fragment/transparentShader.glsl
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp
- SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
Testing: Added a slider for controlling the intensity of the emissive
> THO-906 adding emissive intensity

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnPoint.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Wwise_IDs.h
Small upgrade to allow the spawn area of the tree be moved away from it. Prefab also contains the final mesh now.
Also contains sounds now when activated.
For testing, go to the task/lg_tol-functionality_THO-022 branch in the game repo and place the TreeOfLife prefab.
> Tree of life audio and spawnpoint

- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.cpp
New version of the ultimate attack. 
For now is implemented in the tutorial scene. It is known that the VFX it dissapears when player finishes its animation. In a future pr, this would be fixed.
to test:
- go to Ultimate_new_version branch in game repository.
- Go to Tutorial Scene.
- test how it looks the ultimate ingame.
(It is known that there is some bug in the map that causes the following. I don't know what is caused for, but I believe ultimate does not cause this?).
Anything that you find please report it. Thanks.
> Ultimate vfx v1.1

- SobrassadaEngine/Modules/SceneModule.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj
Testing: Play the game with the last version in game configuration (You can try the other configurations if you want)
> THO-998 bug with game over script

- SobrassadaEngine/FileSystem/Importers/MaterialImporter.cpp
- SobrassadaEngine/FileSystem/Importers/MeshImporter.cpp
- SobrassadaEngine/Modules/LibraryModule.cpp
- SobrassadaEngine/Modules/LibraryModule.h
This PR fixes a crash when using the debug mode, it might need a full engine and project library rebuild to work properly.
> Debug library caching THO-1000

- Game/EngineDefaults/Shader/Fragment/IBLLightingPass.glsl
- SobrassadaEngine/FileSystem/Batching/BatchManager.cpp
- SobrassadaEngine/FileSystem/Batching/BatchManager.h
- SobrassadaEngine/FileSystem/Batching/GeometryBatch.cpp
- SobrassadaEngine/FileSystem/Batching/GeometryBatch.h
- SobrassadaEngine/Scene/Components/Standalone/Lights/DirectionalLightComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Lights/DirectionalLightComponent.h
- SobrassadaEngine/Scene/RenderPass.cpp
- SobrassadaEngine/Scene/RenderPass.h
For me shadows are working good now. 
Also I added a little more smooth in the PCF and I added a shadow Strength variable (PCF also reduces the shadow intensity).
For testing: Just play the game. You can touch the directional to see better the shadows (In level 1, there is more than 1 directional, the engine only support one at the same time, you can try other levels or gl searching)
> THO-949 shadow render fix

- SobrassadaEngine/Scene/Components/Standalone/Lights/DirectionalLightComponent.cpp
- SobrassadaEngine/Scene/Components/Standalone/Lights/SpotLightComponent.cpp
- SobrassadaEngine/Scene/RenderPass.cpp
Testing:
Add a spotlight and see shadows work correctly
> THO-997 spot light rendering issue

- SobrassadaEngine/Scene/RenderPass.cpp
This should fix the engine flicker when resizing the imgui ui.
> THO-1015 Engine UI flicker

- SobrassadaEngine/Modules/GameUIModule.cpp
- SobrassadaEngine/Modules/ShaderScriptModule.cpp
- SobrassadaEngine/Modules/ShaderScriptModule.h
- SobrassadaEngine/Scene/Components/ComponentUtils.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.h
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/UISpritesheet.cpp
- SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/UISpritesheet.h
This task adds 3 new player vfx: Screen fire when riastrad mode, new texture when aiming and particles for the spear.
TO TEST: Go to player-vfx-adjustments game branch and see if they work.
Known issue: the riastrad fire spritesheet sometimes has a line across the screen, but we decided to put it anyway for now and fix it later. Also the spear particles and trail is WIP
> task/Three more player VFX
