TheCenturiaGames/Sobrassada_Engine

SobrassadaEngine/Scene/GameObjects/GameObject.cpp
Has been disabled drag and drop when the source gameObjects is the Scene GameObject (Root GameObject).
=> Fixed Drag & Drop Scene GameObject

SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp, SobrassadaEngine/Utils/LightsConfig.cpp, SobrassadaEngine/Utils/Scene.cpp
Fixed loading twice a mesh or material crashed the application. 
Also, I was debugging and thinking that if we close the scene, all resources should be deleted.
=> bug/loadTwice THO-177

SobrassadaEngine/Modules/ResourcesModule.cpp
When a resource is created and returned its reference count was not incremented. That led to the issue that is described in the bug report
=> Fixed bug with wrong resource reference count

SobrassadaEngine/Application.cpp, SobrassadaEngine/Modules/EditorUIModule.cpp, SobrassadaEngine/Modules/EditorUIModule.h, SobrassadaEngine/Scene/Components/ComponentUtils.h, SobrassadaEngine/Scene/GameObjects/GameObject.cpp
Fixed two memory leaks. 
- EngineConfig did not get deleted
- static list in ComponentUtils showed as memory leak, according to Marc its an issue in the vs debugger. Still removed it though
=> Fixed memory leaks in EngineConfig and ComponentUtils - THO-224

SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp
Added movement in X-axis as a request from the art team. Now keys "A" and "D" makes horizontal movements.
To mahe coherence with rotation, now rotation keys are binded with "Q" (rotate left) and "E" (rotate right).
In order to test this, create a gameObject with a mesh component as a child and the parent should have the character Controller component. Once in play mode, play with WASDQE keys.
NOTE: Has been found a bug when play button is pressed and afterwards  stop button is pressed more than once, it unables to execute the engine. To solve this, you are forced to delete the save scene that was using. It is unknown if this bug has been solved in VS2 branch.
=> Update keys mov character controller tho 324

SobrassadaEngine/DirectXTex/DirectXTex/DirectXTex_Desktop_2022.vcxproj, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj, SobrassadaEngine/SobrassadaEngine.sln, SobrassadaEngine/SobrassadaEngine.vcxproj
If someone downloads releases builds, they don't need to have Visual Studio installed to run .exe
Optick will be available in Profile and GameDebug configs now.
How to test:
Run Profile config and check that Optick works in this config.
Run Release and Optick shouldn't work.
=> task/Moved Optick from Release to Profile config

SobrassadaEngine/Modules/DebugDrawModule.cpp, SobrassadaEngine/Modules/SceneModule.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.h, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scene/Scene.h, SobrassadaEngine/Utils/RaycastController.cpp
Adds the multi selection feature.
To test:
Add different game objects / models to the scene and by holding Left Shift and clicking objects AABB should render arround the selected ones and by moving the gizmo all objects should move together.
I know that those objects dissapear temporarily from the tree node view (code limitations).
Clicking outside the scene window or just left clicking should restore the tree view and all multiselected objects should stop rendering the AABB.
=> THO-334 Multiple Selection

SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.h
Now the player is able to walk though the navmesh, similar that the AI Agent component does. It clamps the position outside the borders of the navMesh in order to not fall and also in holes that could possibly have the navMesh inside.
To make things easier, a manual gravity has been applied in characterControllerComponent to control the height between the player and the navMesh. If we need to check this let me know and we can reformulate that part, but at the moment it works perfectly fine.
To test this:
Create a Scene with some gameObjects that work as a floor and some obstacles
Create some objects that can work as a height to be able to climb them.
Once the scene is created, create the navMesh and adjust the parameters according to the test you want to try.
After NavMesh is created, …
=> Player movement controller update 2 THO-212

SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp, SobrassadaEngine/Modules/SceneModule.cpp, SobrassadaEngine/Modules/SceneModule.h, SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.h, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/Physics/CapsuleColliderComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/Physics/CubeColliderComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/Physics/SphereColliderComponent.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.h, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scene/Scene.h
Adds hability to copy and delete game objects even inside a multiselection.
Also now nodes in Models have their node name instead of the filename (reinport them before testing)
If you want to delete in multiselection use the hotkey, if you try to delete with the button the multiselection  is cleared to avoid further bugs with other options in the engine.
=> THO-364 QoL Improvements artist feedback

SobrassadaEngine/FileSystem/Importers/MeshImporter.cpp, SobrassadaEngine/FileSystem/Importers/MeshImporter.h, SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp, SobrassadaEngine/Modules/EditorUIModule.cpp, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp
This pr contains necessary adaptions to correctly import artist gltfs
Main changes:
Fixed issue when loading gltfs without material (Default materials diffuse texture is not changed anymore to the fallback texture)
GLTF loading is now based on nodes rather than meshes. The nodes are iterated and load their assigned meshes and primitives. That solves an issue we had when loading default transforms (It needed the name of the node and mesh to be the same which was not the case for artist gltfs)
For testing: Import gltfs and see if everything works as previously
=> Task/lg load gltf default material THO-380 THO-381

SobrassadaEngine/Modules/SceneModule.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.h, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scene/Scene.h
The title explains, also there is a bug that the mobility settings of duplicated game objects are wrong.
To test: Create dynamic and static game object, multiselect them and start duplicating, check they mantain their mobility setting.
=> THO-387 Duplication in multiselect in VS2 merge 0.3.3 crashes if colliders

SobrassadaEngine/FileSystem/Importers/MeshImporter.cpp, SobrassadaEngine/FileSystem/Importers/MeshImporter.h, SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp, SobrassadaEngine/FileSystem/Importers/SceneImporter.h, SobrassadaEngine/FileSystem/Meta/MetaMesh.cpp, SobrassadaEngine/FileSystem/Meta/MetaMesh.h, SobrassadaEngine/Modules/LibraryModule.cpp
With the recent changes regarding naming of assets, the import of meshes from meta files was broken.
This pr solves that issue. It finds the primitives of a gltf now based on indices of gltf arrays instead of name comparisons.
For testing:
- import fresh gltfs into the engine (old meta files won´t work anymore)
- save scene with objects placed
- close engine, delete library folder, reopen it
- the meshes should be loaded correctly
=> Bug/lg mesh import from meta THO-388

SobrassadaEngine/Main.cpp, SobrassadaEngine/Modules/CameraModule.cpp, SobrassadaEngine/Modules/EditorUIModule.cpp, SobrassadaEngine/Modules/EditorUIModule.h, SobrassadaEngine/Modules/ScriptModule.cpp, SobrassadaEngine/Modules/ScriptModule.h, SobrassadaEngine/Scene/Components/CameraComponent.cpp, SobrassadaEngine/Scene/Components/CameraComponent.h, SobrassadaEngine/Scene/Components/ScriptComponent.cpp, SobrassadaEngine/Scene/Components/ScriptComponent.h, SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.h, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ButtonScript.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/GodMode.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/GodMode.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/RotateGameObject.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/RotateGameObject.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters, SobrassadaEngine/Utils/Script.h
Added godCamera and ImGui integration in scripting.
Test:
For god camera you can add a mesh, a character controller a godcamera script in a gameobject and a camera in a child gameobject. When you click play you can press P to detach the camera and inutilice the input of the player. You can attach the camera clicking O.
For ImGui Integration you can see rotateGameObject (only works the speed, the other ones are a test)
Remember to create a navmesh.
=> Engine functions while playing THO-232

SobrassadaEngine/Modules/SceneModule.cpp, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scene/Scene.h
Now if you duplicate in multiselect, duplicated spawn on the OG position instead of 000.
I know if you move the multiselection and duplicate, the dupes spawn at the original position, but this shit is too hard to manage, haver a good day.
😶‍🌫️
=> THO-397-Multiselect-duplication-spawn

SobrassadaEngine/Scene/Components/CameraComponent.cpp, SobrassadaEngine/Scene/Components/CameraComponent.h, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Utils/LightsConfig.cpp
You can delete cameraComponent now. Also camera in prefabs works now. Also solved a bug where skybox does not work in a new scene
For testing: You can try all of these things
=> THO-485 camera in prefab not working

SobrassadaEngine/FileSystem/Importers/AnimationImporter.cpp, SobrassadaEngine/FileSystem/Importers/FontImporter.cpp, SobrassadaEngine/FileSystem/Importers/MaterialImporter.cpp, SobrassadaEngine/FileSystem/Importers/ModelImporter.cpp, SobrassadaEngine/FileSystem/Importers/NavmeshImporter.cpp, SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp, SobrassadaEngine/FileSystem/Importers/TextureImporter.cpp
All metafiles now keep their UID if they existed before and are overwritten by a new import.
This ensures that previous established links, for example between a mesh and its material, are not broken after a reimport.
Test with importing various files and see if the meta files keep their UID
=> Meta override while keeping UID

SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.h, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Utils/RaycastController.cpp
Mouse picking inverted, so now only nodes with select parent checkbox skip to the next parent, when loading a model, all children are set with this checkbox.
Also, now clicking on a game object expands the tree view upwards.
=> THO-476 Invert mouse picking

SobrassadaEngine/FileSystem/Importers/AnimationImporter.cpp, SobrassadaEngine/FileSystem/Importers/AnimationImporter.h, SobrassadaEngine/FileSystem/Importers/ModelImporter.cpp, SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp, SobrassadaEngine/FileSystem/Importers/SceneImporter.h, SobrassadaEngine/FileSystem/Meta/MetaAnimation.cpp, SobrassadaEngine/FileSystem/Meta/MetaAnimation.h, SobrassadaEngine/Modules/LibraryModule.cpp, SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.h, SobrassadaEngine/Utils/Globals.h
This PR fixes few things with the animation import and component.
Animation are now properly reimported from metafiles if the library is deleted, also selecting an animation in the dropdown of the component editor assigns that animation to the component.
In order for the changes to work existing models with animations need to be reimported so the metafile gets updated with the index in the model.
You can try with the artist model which contains one animation and with the fox which contains 3, once imported and deleting the library, once the scene is opened the models should mantain their animations.
=> THO-484 Meta animation wrong file path

SobrassadaEngine/Modules/PhysicsModule.cpp, SobrassadaEngine/Scene/Components/ComponentUtils.h
Added two new physics layers the player and enemy projectile.
**Important!** If you load an existing scene you will need to add the collision config on the editor settings, if a new scene is created it will take the default values.
Default values:
Player projectile -> enemies
Enemy projectile -> player
Player-> also interacts with enemy projectile
=> THO-496 Added new projectile layers for player and enemy

SobrassadaEngine/Scene/Scene.cpp
This PR fixed a bug when the user attempts to load a prefab with a corrupted file. 
For testing, modify a prefab file so that the json syntax is broken. 
The engine should not crash and a log with the error is displayed in the console.
=> Fixed crash when a broken prefab file is being loaded

SobrassadaEngine/FileSystem/Importers/MaterialImporter.cpp, SobrassadaEngine/FileSystem/Importers/TextureImporter.cpp, SobrassadaEngine/FileSystem/Importers/TextureImporter.h
This pr fixes an import problem which prevented textures with the same name to be overwritten by new versions. 
To test, go to the AssetOverview scene of the EngineTest repo and import the following gltf: 
https://drive.google.com/file/d/1xKrhXlu4QHt5E88QBw5jTtoMhnm1l2uw/view?usp=sharing
After importing, the pillars should switch from a blue texture to a grey texture. Before this change they stayed blue.
=> Allowed textures to be overwritten by new versions THO-502

SobrassadaEngine/Application.cpp, SobrassadaEngine/Application.h, SobrassadaEngine/Modules/DebugDrawModule.cpp, SobrassadaEngine/Modules/DebugDrawModule.h, SobrassadaEngine/Modules/EditorUIModule.h, SobrassadaEngine/Modules/GameDebugUIModule.cpp, SobrassadaEngine/Modules/GameDebugUIModule.h, SobrassadaEngine/SobrassadaEngine.vcxproj, SobrassadaEngine/SobrassadaEngine.vcxproj.filters
Added GameDebugUIModule, only renders stuff if in game or game debug build, in order to make the menu appear hit F1, there is only the fps, a checkbox to spawn the console and a button to close the game properly. Also, if you hit F2 the render options menu appears.
=> Tho 495 Engine debugs in game build

SobrassadaEngine/FileSystem/Importers/SceneImporter.cpp
Fixed bug which loads meshes in the wrong order. The order of the meshes in models in the engine was determined on the node order which broke links in specific cases. Now the mesh order is the same as it is in the gltf.
When importing the provided gltf, the animation should run perfectly.
[Attack1.zip](https://github.com/user-attachments/files/20163850/Attack1.zip)
=> Fixed bug which loads meshes in the wrong order

Game/EngineDefaults/Shader/Fragment/DepthFragment.glsl, Game/EngineDefaults/Shader/Fragment/QuadFragment.glsl, SobrassadaEngine/FileSystem/Batching/BatchManager.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.h, SobrassadaEngine/Modules/CameraModule.h, SobrassadaEngine/Modules/DebugDrawModule.h, SobrassadaEngine/Modules/ShaderModule.cpp, SobrassadaEngine/Modules/ShaderModule.h, SobrassadaEngine/Scene/Components/CameraComponent.h, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scene/Scene.h, SobrassadaEngine/Utils/GBuffer.h, SobrassadaEngine/Utils/Globals.h
Testing: There are 3 new render debugs. GBuffers, Depth where you see the textures and Navmesh meshes. All the meshes with NavMesh Valid are rendered normally and the ones without the checkbox is rendered as wireframe. Remember to have objects on scene with the option and without it to see anything
=> THO-61 debug view navmesh meshes prefab

SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters
Now the fire trap base serves as the main position anchor, so the pivot for moving it around is in the middle of the trap itself. 
Also improved efficency of distance calculation to the player.
For testing, go to dev-test and open the Fire ball scene and check that the pivot for the trap is at the center and the trap still works
=> Updated fireball trap to work with new hierarchy THO-634

Game/EngineDefaults/Shader/Fragment/gBufferMetallicFragment.glsl, Game/EngineDefaults/Shader/Fragment/gBufferSpecularFragment.glsl, SobrassadaEngine/FileSystem/Batching/BatchManager.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.h, SobrassadaEngine/FileSystem/Importers/MaterialImporter.cpp, SobrassadaEngine/FileSystem/Material.h, SobrassadaEngine/FileSystem/Meta/MetaMaterial.cpp, SobrassadaEngine/FileSystem/Meta/MetaMaterial.h, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
Testing: Added double side rendering. It has a checkbox in the material for already imported meshes.
Also added a condition in opaque objects to solve the bug of seeing transparent instead of black.
I added the plants as a good example of a double side render. You can enable/disable to check the rendering
[TEST.zip](https://github.com/user-attachments/files/20401154/TEST.zip)
=> THO-624 two sided rendering

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/FireballTrap.h
Changed the fire trap dropping behaviour and added a mockup shadow for marking where the fireball is falling.
To test:
- Create a game object with a sphere collider, a mesh plane and a script with the fireball script added
- As children, add first a cube as the projectile and then a second plane as the shadow
- Play
=> Task/fire trap improvements THO-640

Game/EngineDefaults/Shader/Fragment/gBufferMetallicFragment.glsl, Game/EngineDefaults/Shader/Fragment/gBufferSpecularFragment.glsl, Game/EngineDefaults/Shader/Fragment/transparentShader.glsl, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h, SobrassadaEngine/Scene/Components/Standalone/AIAgentComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/AIAgentComponent.h, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Banshee.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Banshee.h
Implemented the new banshee behaviour as it was discussed. Now the banshee no longer flees. When the player is detected, it chases it until a set distance, then disappears and after a random amount of time appears next to the player, attacks, disappears again, attacks, etc. If the player gets far it is chased again or even stops chasing it.
The changes on shaders and materials do nothing for now, I tried some things with Andreu to make the banshee disappear smoothly tweaking the alpha, but there were more problems than we expected, so for now it directly disables and enables the mesh. That will be done in a future task.
To test you can go to the level 2 of the game repo and see if it works fine. Raise chase range and the attack range of the banshee, so it disappears further away from the …
=> task/New banshee behaviour THO-720

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Archer.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Archer.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
Just a small change which makes each archer get their own arrow reference, without needing a name. To test, play a level which has archers and test if they shoot properly as before.
=> task/Archer arrow projectile name THO-714

SobrassadaEngine/Scene/Components/Standalone/CharacterControllerComponent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CameraMovement.cpp
Fixed the camera movement when the framerate drops too much / delta time increases too much. 
Previously happened when loading a new scene during play or when playing on a low performance pc.
For testing, you can use the following code to artifically increase frame duration (Just put it somewhere in the update loop): 
std::this_thread::sleep_for(std::chrono::milliseconds(15));
You should see a varity of bugs including the player falling through the floor and it not being able to move properly. Those issues will be adressed later. What should work is the camera, it should stay focused on the player all the time.
=> Camera movement bug

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/OptionsMenuSwitcherScript.cpp
Updated the references of the UI for the cooldown and the UI controller Menu for alpha1 in The Hound of Ulster Repository.
In order to test this:
- make a dash or ultimate attack on level 2 and see if it works the change of the icons of the skills.
- in options menu (main menu scene), check that changes the button navigation of the menu when using a controller and changes back when using keyboard.
=> UIDs changed for cooldown and options menu for alpha1

SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h, SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.cpp, SobrassadaEngine/ResourceManagement/Resources/ResourceStateMachine.h, SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Character.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.h, SobrassadaEngine/UI/EngineEditors/Editor/StateMachineEditor.cpp
This PR adds various features, most of them for the player:
- The player has new animations: heal, hurt and transform, as well as some other have been updated like the running one.
- Added vfx when transforming to riastrad. The player also turns red (this is provisional, to have visual feedback). I also added a little slow-motion in a part of the animation, if you don't like it tell me and I can remove it.
- Also added the "cursed" state, where the player moves slower and cannot dash. This will be triggered by the changeling, for now it's triggered pressing the F9 key. It also changes the color of the character for now.
- Added a knockback area when healing and transforming.
Some other new things:
- Now the MovingUVTransparent has a double-sided check in the inspector.
- Added a button to …
=> New iteration of player final version

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.h
In order to create some progression, player will have locked some skills from the start. In some specific conditions, player will unlock skills.
The code has been adapted to lock or unlock any skill. In this case only has been implemented dash mechanic with this feature.
To control which skills are unlocked in the level, properties in CuChulain script added to unlock abilities from start. In spawnUI has been added also some properties to activate the skill you want to activate (for UI purposes).
How to test it:
- In The Hound of Ulter repository, go to branch Player progression. Tutorial level and lvl 1 adapted to test this functionality.
- from start, dash UI and dash functionality are locked.
- go to Dash tutorial. This unlocks dash mechanic and UI.
- When changes from tutorial to lvl …
=> Player progression (lock & unlock skills) final Player THO-777

Game/EngineDefaults/Shader/Custom/Fragment/MovingUV_PostL_Fragment.glsl, Game/EngineDefaults/Shader/Custom/Vertex/MovingUV_Light_Vertex.glsl, Game/EngineDefaults/Shader/Custom/Vertex/MovingUV_PostL_Vertex.glsl, SobrassadaEngine/FileSystem/Batching/BatchManager.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.h, SobrassadaEngine/Modules/ShaderScriptModule.cpp, SobrassadaEngine/Modules/ShaderScriptModule.h, SobrassadaEngine/Scene/Components/ComponentUtils.h, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.h, SobrassadaEngine/Scene/RenderPass.cpp, SobrassadaEngine/Scene/Scene.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.cpp
Moving UV shaders now are compatible with meshes using animations, it also adds the option to use shader scripts after the particles and billboards, options is called Post Effects.
=> THO-879 Bones in moving uv shaders

Game/EngineDefaults/Shader/Custom/Vertex/MovingUV_Light_Vertex.glsl, SobrassadaEngine/Scene/Components/Standalone/AnimController.cpp, SobrassadaEngine/Scene/Components/Standalone/AnimController.h, SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.cpp, SobrassadaEngine/Scene/Components/Standalone/MeshComponent.h, SobrassadaEngine/Scene/GameObjects/GameObject.cpp, SobrassadaEngine/Scene/RenderPass.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVLight.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVPostScript.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MovingUVTransparent.cpp
This adds the scaling to the transform for animations which were not used, needed for VFX mesh animations. It also fixes an error that happend during merge that broke the transparent moving uv shader.
If you want to test with a mesh and animation that contains scaling: 
[shoutstart.zip](https://github.com/user-attachments/files/21761145/shoutstart.zip)
=> THO-892 Animation scales

Game/EngineDefaults/Shader/Vertex/VertexShader.glsl, SobrassadaEngine/FileSystem/Batching/BatchManager.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.cpp, SobrassadaEngine/FileSystem/Batching/GeometryBatch.h, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.cpp, SobrassadaEngine/ResourceManagement/Resources/ResourceMaterial.h
Adds a checkbox to the material wind parameters which removes all position or uv based variables from the vpo calculation. 
This results in the possibility to create objects which just gently sway around without deforming, planned for usage in magic environment rocks.
For testing, just apply the wind to any mesh and check the use constant movement checkbox. The mesh should not deform anymore, only move, while all other controls stay functional. 
Also test that this change does not break the normal wind shader when the constant movement is disabled.
=> Constant vpo for magical objects

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Soldier.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Soldier.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Wwise_IDs.h
PR fixing 2 bugs and adding audio to the attacks of the Soldier. Wanted to include the changing helmets functionality to this PR but i didn't get the meshes at time so i priorized having the bugs fixed.
To test:
-Go tho the SoldierNewRig branch at the game repo in Level 1
-Check the Soldier now doesen't dissapear when killing the player
-Check The trail now works correctly
-Check the audio is correct when the soldier attacks. It has a different audio for each attack.
=> Task/Soldier Bugs fixing + attack audio

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp
I couldn't test it because to me in alpha 2 archers don't shoot and teleport around, but this should fix the crash
=> fix arrow crash

SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Destructible.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Destructible.h
This PR changes the base class of the destructible script from a character to a normal script to reduce complexity and increase performance. 
For testing, go to the same branch in the game repo and add the All_Tributes_Destructible prefab to a scene. The destructibles should work like normal while also playing sounds now
=> Destructibles V3 THO-1012

SobrassadaEngine/Modules/InputModule.cpp, SobrassadaEngine/Modules/InputModule.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SpawnUI.h
This PR adds the functionality to change the tutorial UIs depending on the selected input devices. 
Supported are keyboard, dualshock and xbox, with the xbox ui showing for all controllers which aren´t dualshocks.
Also adds the option to show ui only once, and for it to disappear after x seconds.
I don´t have an xbox controller for testing, so at least one tester should test with that.
For testing, go to the same branch in the game repo. The movement tutorial works like previously, only showing the correct controls for the input device. The dash tutorial is triggered only once and disappears after 5 seconds
Known issues: 
There are ui elements in the main menu and health bar which are not showing the proper controls. These will be tackled with a later pr / change in the scene
=> Tutorial input device UI  THO-916

SobrassadaEngine/Scene/Components/Standalone/AnimationComponent.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/CuChulainn.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Projectile.h
A new clean version of the ultimate attack. In this PR has been added:
- Ultimate polished animation.
- Adjusted shader script used in ultimate.
- SFX for heal, death & range attack.
How to test it:
- go to Player_ulti_sfx branch in game repository.
- Test in tutorial scene and check if it works correctly. (in other levels not implemented)
Note: any feedback is welcome in order to modify it in this PR or in a next one. Due to an error that I found while implementing, I tried include a spritesheet for the ultimate but didn't work. In the next PR will be included.
=> Player ultimate & SFXs

SobrassadaEngine/Modules/EditorUIModule.cpp, SobrassadaEngine/Scene/Components/ScriptComponent.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/GameOverNavigatorScript.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MusicManager.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MusicManager.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MusicTrigger.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/MusicTrigger.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Script.h, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/ScriptExport.cpp, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/SobrassadaScripts.vcxproj.filters, SobrassadaEngine/Scripting/SobrassadaScripts/SobrassadaScripts/Wwise_IDs.h, SobrassadaEngine/Utils/Script.h
This PR adds scripts to dynamically control which music track is played in which level and area. 
Once the player enters a dedicated collider the music will change smoothly. 
For testing. open the same branch in the game repo. When spawning, no music is playing. If you continue to walk through the level music will start, and then switch to different tracks once at the end of the fireball area and once at the tree of life behind the bridge. The associated colliders disappear once activated. They are all enabled again once the player respawns (Can no be tested directly as the ui is broken)
Known issues: If there are compile errors in the soldier script just comment out the lines for testing, this problem will disappear with the alpha 3 merge
=> Adaptive music THO-1014
